name: ube_fit_challenge
description: "UBE Fit Challenge App"
publish_to: 'UBE Group'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  # equatable: ^2.0.7
  # shared_preferences: ^2.3.5
  # firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  # firebase_storage: ^12.4.1
  # image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.3

flutter_icons :
  android: true
  image_path: 'assets/logo/AppLogo.png'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets :
    - assets/logo/
    - assets/icons/
    - assets/text/
