// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWPTekQpnq7Qv-3S5DfesJIvfLJhfMe-k',
    appId: '1:558393215196:android:c98671bc1f0c45481e8c19',
    messagingSenderId: '558393215196',
    projectId: 'ube-fit-challenge',
    storageBucket: 'ube-fit-challenge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMXO6Uk0uAROU5FmjJI7z8RykG0-2vY4o',
    appId: '1:558393215196:ios:eb56329354d468561e8c19',
    messagingSenderId: '558393215196',
    projectId: 'ube-fit-challenge',
    storageBucket: 'ube-fit-challenge.firebasestorage.app',
    iosBundleId: 'com.example.ubeFitChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMXO6Uk0uAROU5FmjJI7z8RykG0-2vY4o',
    appId: '1:558393215196:ios:eb56329354d468561e8c19',
    messagingSenderId: '558393215196',
    projectId: 'ube-fit-challenge',
    storageBucket: 'ube-fit-challenge.firebasestorage.app',
    iosBundleId: 'com.example.ubeFitChallenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL3Y8ZCKGFr7nyzW9_WAm7h5jvyB6m0nM',
    appId: '1:558393215196:web:df3be6d700df4dd41e8c19',
    messagingSenderId: '558393215196',
    projectId: 'ube-fit-challenge',
    authDomain: 'ube-fit-challenge.firebaseapp.com',
    storageBucket: 'ube-fit-challenge.firebasestorage.app',
    measurementId: 'G-40F51XX4L7',
  );
}
